name: Sync main branch to demo brach

on:
  push:
    branches:
      - main
      - demo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@v2
        with:
          ref: demo  # Operate within the `demo` branch

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch and merge main into demo
        run: |
          git fetch origin main
          git merge origin/main --no-edit
          git push origin demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
